# Generated by Django 5.0.2 on 2024-02-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_product_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to='product/'),
        ),
    ]
