# Generated by Django 5.0.2 on 2024-02-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tour',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=56, null=True),
        ),
    ]
